config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'users', to: 'users#index'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(10) }
end

app/models/user.rb
# User Model
class User < ApplicationRecord
  validates :username,
            presence: true,
            length: {
              minimum: 3, maximum: 15
            },
            uniqueness: {
              case_sensitive: false
            }
  has_many :messages
  has_secure_password
end

app/controllers/application_controller.rb
#  Application
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    if !logged_in?
      flash[:error] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
# Chatroom Controller
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
# Messages Controller
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'chatroom_channel',
                                   mod_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: message })
  end
end

app/controllers/sessions_controller.rb
# Sessions Controller
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]

  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid login credentials'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Hey there, #{@user.username}! Welcome to MessageMe"
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid sign up credentials'
      render 'new'
    end
  end

  def show; end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned medium icon header">
  <i class="inverted teal circular gem icon" id="gem-icon"></i>
  Say something
</h2>

<div class="ui stackable two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content" id="messages">
        <div class="ui feed" id="message-container">
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
        <div class="field">
          <div class="ui fluid icon input">
            <%= f.text_field :body, placeholder: 'Type your message here...' %>
            <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <%= link_to  "Home", root_path, class: "active item" %>
          <%= link_to  "Friends", users_path, class: "item" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui huge fixed inverted menu">
  <div class="item">
    <%= image_tag("logo.png") %>
  </div>
  <%= link_to "Chatroom", root_path, class: "item" %>
  <div class="right menu">
    <div class="ui dropdown item">
      Account <i class="dropdown icon"></i>
      <div class="menu">
        <% if logged_in? %>
          <%= link_to "Logout", logout_path, method: :delete, class: "item" %>
        <% else %>
          <%= link_to "Log in", login_path, class: "item" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <% favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render  "layouts/navigation" %>
    <div class="ui container">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      <em><%= message.user.username %></em>: <%= message.body %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<hr>
<% @users.each do |users| %>
  <h4><%= users.username %></h4>
<% end %>

app/views/users/new.html.erb
<%= form_for(@user, :html => {class: "ui form", role: "form"}) do |f| %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username, placeholder: "Enter username...", autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password..." %>
  </div>
  <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "ui button") %>
<% end %>